name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: clang -m64 -O3 -Wall -lpthread -o thread_socket thread_sock.c
