name: C CI

on:
  push:
    branches: [ "main" ]
    tags: "latest"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: Test
      run: ./thread_socket -h
      
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Create release
      uses: softprops/action-gh-release@v1
      id: create_release
      with:
        files: thread_socket
        token:
          "sdk250.."

